### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by ZhenjiaYY** [KaoruNishikawa/ros1_test#2]
Thanks for your work. I want to know how to use this tools？

**Comment by KaoruNishikawa** [comment]
@ZhenjiaYY 
Thanks for having interest in this repository!
I'll prepare a brief README (including the usage) in a day or two, so check if this repo meets your needs then.

**Comment by KaoruNishikawa** [comment]
@ZhenjiaYY 
I've drafted the docs.
If something remains unclear, feel free to reopen this issue or create new one.
